language: python
python:
  - "3.4"
env:
  - CONFIG=config.CIConfig
services:
  - postgres
install: "pip install -r requirements.txt"
before_script: "python manage.py db setup"
script:
  - make lint
  - make coverage